local py_void_well = {
	name = "py_void_well",
	icon = "__void-miners-extended__/graphics/icons/void-well.png",
	icon_size = 32,
	--order
	type = "assembling-machine",
	max_health = 300,
	minable = {mining_time = 0.5, result = "py_void_well"},
	animation = {
		filename = "__void-miners-extended__/graphics/entity/void-well/void-well.png",
		priority = "high",
		height = 64,
		width = 64,
		frame_count = 1,
		line_length = 1,
	},
	open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.5},
	close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.5},
	repair_sound = {filename = "__base__/sound/manual-repair-simple.ogg", volume = 1},
	mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg", volume = 1},
	vehicle_impact_sound = {{filename = "__base__/sound/car-crash.ogg", volume = 1}},
	working_sound = {filename = "__void-miners-extended__/sound/void-well-working.ogg", volume = 0.5},
	open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.5},
	close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.5},
	repair_sound = {filename = "__base__/sound/manual-repair-simple.ogg", volume = 1},
	mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg", volume = 1},
	vehicle_impact_sound = {{filename = "__base__/sound/car-crash.ogg", volume = 1}},
	working_sound = {filename = "__void-miners-extended__/sound/void-well-working.ogg", volume = 0.5},
	corpse = "medium-remnants",
	dying_explosion = "medium-explosion",
	flags = {"placeable-player", "player-creation"},
	collision_box = {{-0.8, -0.8}, {0.8, 0.8}},
	selection_box = {{-1, -1}, {1, 1}},
	energy_source = {
		type = "electric",
		usage_priority = "secondary-input",
		emissions_per_minute = 1,
	},
	fluid_boxes = {{
        production_type = "output",
        pipe_covers = pipecoverspictures(),
        base_area = 10,
        base_level = 1,
        pipe_connections = {{
            type = "output",
            position = {0.5, 1.5}
        }}
    }},
	crafting_categories = {"void-well-mining","void-well-mining-bz","void-well-mining-py"},
	crafting_speed = 2,
	energy_usage = "108MW",
	fast_replaceable_group = "void-miners",
	module_specification = nil,
	allowed_effects = nil,
	next_upgrade = "",
}
 local py_void_miner = {
	name = "py_void_miner",
	icon = "__void-miners-extended__/graphics/icons/py-void-miner.png",
	icon_size = 64,
	--order
	type = "assembling-machine",
	max_health = 500,
	minable = {mining_time = 0.5, result = "py_void_miner"},
	animation = {
		animation_speed = 0.9,
		filename = "__void-miners-extended__/graphics/entity/py-void-miner/py-void-miner.png",
		priority = "high",
		height = 122,
		hr_version = {
			animation_speed = 0.9,
			filename = "__void-miners-extended__/graphics/entity/py-void-miner/hr-py-void-miner.png",	
			priority = "high",
			height = 242,
			width = 365,
			frame_count = 16,
			line_length = 8,
			scale = 0.5,
			shift = {1.8, -0.2}
		},
		width = 184,
		frame_count = 16,
		line_length = 8,
		scale = 0.9,
		shift = {1.65, -0.175}
	},
	se_allow_in_py = true,
	open_sound = {filename = "__base__/sound/machine-open.ogg", volume = 0.5},
	close_sound = {filename = "__base__/sound/machine-close.ogg", volume = 0.5},
	repair_sound = {filename = "__base__/sound/manual-repair-simple.ogg", volume = 1},
	mined_sound = {filename = "__core__/sound/deconstruct-medium.ogg", volume = 1},
	vehicle_impact_sound = {{filename = "__base__/sound/car-crash.ogg", volume = 1}},
	working_sound = {filename = "__void-miners-extended__/sound/void-miner-working.ogg", volume = 0.3},
	corpse = "medium-remnants",
	dying_explosion = "medium-explosion",
	flags = {"placeable-player", "player-creation"},
	collision_box = {{-1.2, -1.2}, {1.2, 1.2}},
	selection_box = {{-1.5, -1.5}, {1.5, 1.5}},
	module_specification = {
		module_slots = 4,
    },
	allowed_effects = {"speed", "productivity", "consumption", "pollution"},
	energy_source = {
		type = "electric",
		usage_priority = "secondary-input",
		emissions_per_minute = 1,
	},
	crafting_categories = {"void-mining","void-mining-bz","void-mining-py"},
	fast_replaceable_group = "void-miners",
	crafting_speed = 2,
	energy_usage = "108MW",
	result_inventory_size = 1,
	next_upgrade = "",
}
    data:extend({
	py_void_well,
	py_void_miner,
    })